
name: Run Automated Tests

# This section defines the trigger for the workflow
on:
  # Run this workflow on every push to the 'main' or 'master' branch
  push:
    branches: [ main, master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# This section defines the jobs that will run
jobs:

  run-tests:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a standard Linux environment.
    runs-on: ubuntu-latest

    # These are the sequential steps that will be executed in the job
    steps:
      # Step 1: Checks out repository's code so the job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Sets up the Java Development Kit (JDK) on the virtual machine
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      # Step 3: Runs the tests using testng.xml file
      - name: Run Tests with Maven
        run: mvn clean test -B -Dsurefire.suiteXmlFiles=testng.xml